INSERT INTO EMPLOYEES (ID, NAME, AGE) VALUES (1, 'テスト1', 23);
INSERT INTO EMPLOYEES (ID, NAME, AGE) VALUES (2, 'テスト2', 30);
INSERT INTO EMPLOYEES (ID, NAME, AGE) VALUES (3, 'テスト3', 28);
INSERT INTO EMPLOYEES (ID, NAME, AGE) VALUES (4, 'テスト4', 35);
INSERT INTO EMPLOYEES (ID, NAME, AGE) VALUES (5, 'テスト5', 22);